// Emits `crates/smartformat/src/fmt/culture/generated.rs`: the `CultureData`
// table the Rust port formats with, read straight out of .NET's own
// `CultureInfo` rather than mapped from CLDR, so a listed culture formats
// byte-identically to .NET by construction.
//
//     dotnet run --project tools/culturegen > crates/smartformat/src/fmt/culture/generated.rs
//     cargo fmt --all
//
// See tools/culturegen/README.md.

using System.Globalization;
using System.Runtime.InteropServices;
using System.Text;

// The cultures the port ships. Keep this list in step with the table in
// tools/culturegen/README.md.
string[] requested =
[
    "", "en", "en-US", "en-GB", "de", "de-DE", "de-AT", "de-CH", "fr", "fr-FR", "es", "es-ES",
    "es-MX", "it", "nl", "pt", "pt-BR", "pt-PT", "ru", "pl", "cs", "tr", "sv", "da", "fi", "nb",
    "uk", "is", "is-IS", "ja", "ko", "zh-Hans", "zh-CN", "ar", "ar-SA",
];

if (CultureInfo.GetCultureInfo("de-DE").NumberFormat.NumberDecimalSeparator != ",")
{
    throw new InvalidOperationException(
        "globalization is running in invariant mode; culture data would be meaningless");
}

// Sorted the way the Rust `lookup` binary-searches: by ASCII-lowercase name.
var names = requested.Distinct().OrderBy(n => n.ToLowerInvariant(), StringComparer.Ordinal).ToArray();

var w = new StringWriter { NewLine = "\n" };
Emit(w, names);
Console.Out.NewLine = "\n";
Console.Out.Write(w.ToString());

static void Emit(TextWriter o, string[] names)
{
    o.WriteLine("//! .NET culture data for the locales the port ships, read out of");
    o.WriteLine("//! `CultureInfo.NumberFormat` / `.DateTimeFormat` by `tools/culturegen` — not");
    o.WriteLine("//! mapped from CLDR — so every listed culture formats byte-identically to the");
    o.WriteLine("//! .NET that produced it.");
    o.WriteLine("//!");
    o.WriteLine("//! @generated by `dotnet run --project tools/culturegen`. DO NOT EDIT.");
    o.WriteLine("//!");
    o.WriteLine($"//! Generated by {RuntimeInformation.FrameworkDescription} on "
        + $"{RuntimeInformation.OSDescription}. The data");
    o.WriteLine("//! is ICU-backed and therefore tied to that pair, so it has to be regenerated");
    o.WriteLine("//! together with `goldens/m1.json` — see `tools/culturegen/README.md`.");
    o.WriteLine();
    o.WriteLine("use super::{CultureData, DateTimeFormat, NumberFormat};");
    o.WriteLine();
    o.WriteLine("/// Every culture the port ships, sorted by ASCII-lowercase name so [`lookup`]");
    o.WriteLine("/// can binary-search it. The first entry is the invariant culture, which");
    o.WriteLine("/// `culture::get` answers from the hand-written `INVARIANT` instead; a unit");
    o.WriteLine("/// test asserts the two agree.");
    o.WriteLine("pub(super) static CULTURES: &[CultureData] = &[");
    foreach (var name in names)
    {
        EmitCulture(o, name);
    }
    o.WriteLine("];");
    o.WriteLine();
    o.WriteLine("/// Looks up a culture by its full name, case-insensitively like .NET's");
    o.WriteLine("/// `CultureInfo.GetCultureInfo`. No parent fallback: `\"de-XX\"` is not `\"de\"`,");
    o.WriteLine("/// because .NET would resolve it against the whole CLDR tree and we only have");
    o.WriteLine("/// the cultures in [`CULTURES`].");
    o.WriteLine("pub(super) fn lookup(name: &str) -> Option<&'static CultureData> {");
    o.WriteLine("    let index = CULTURES");
    o.WriteLine("        .binary_search_by(|culture| ascii_lowercase_cmp(culture.name, name))");
    o.WriteLine("        .ok()?;");
    o.WriteLine("    Some(&CULTURES[index])");
    o.WriteLine("}");
    o.WriteLine();
    o.WriteLine("/// Orders two culture names the way [`CULTURES`] is sorted. Culture names are");
    o.WriteLine("/// ASCII, so a byte-wise ASCII-lowercase comparison is a full case-insensitive");
    o.WriteLine("/// match, and a non-ASCII argument simply matches nothing.");
    o.WriteLine("fn ascii_lowercase_cmp(a: &str, b: &str) -> std::cmp::Ordering {");
    o.WriteLine("    a.bytes()");
    o.WriteLine("        .map(|byte| byte.to_ascii_lowercase())");
    o.WriteLine("        .cmp(b.bytes().map(|byte| byte.to_ascii_lowercase()))");
    o.WriteLine("}");
}

static void EmitCulture(TextWriter o, string name)
{
    var ci = CultureInfo.GetCultureInfo(name);
    if (ci.Name != name)
    {
        throw new InvalidOperationException($"'{name}' resolved to the different culture '{ci.Name}'");
    }
    var nf = ci.NumberFormat;
    var df = ci.DateTimeFormat;

    o.WriteLine("    CultureData {");
    o.WriteLine($"        name: {Escape(name)},");

    o.WriteLine("        number: NumberFormat {");
    Field(o, "decimal_separator", Escape(nf.NumberDecimalSeparator));
    Field(o, "group_separator", Escape(nf.NumberGroupSeparator));
    Field(o, "group_sizes", Sizes(nf.NumberGroupSizes));
    Field(o, "negative_sign", Escape(nf.NegativeSign));
    Field(o, "positive_sign", Escape(nf.PositiveSign));
    Field(o, "number_decimal_digits", Byte(nf.NumberDecimalDigits));
    Field(o, "number_negative_pattern", Byte(nf.NumberNegativePattern));
    Field(o, "currency_symbol", Escape(nf.CurrencySymbol));
    Field(o, "currency_decimal_digits", Byte(nf.CurrencyDecimalDigits));
    Field(o, "currency_decimal_separator", Escape(nf.CurrencyDecimalSeparator));
    Field(o, "currency_group_separator", Escape(nf.CurrencyGroupSeparator));
    Field(o, "currency_group_sizes", Sizes(nf.CurrencyGroupSizes));
    Field(o, "currency_positive_pattern", Byte(nf.CurrencyPositivePattern));
    Field(o, "currency_negative_pattern", Byte(nf.CurrencyNegativePattern));
    Field(o, "percent_symbol", Escape(nf.PercentSymbol));
    Field(o, "percent_decimal_digits", Byte(nf.PercentDecimalDigits));
    Field(o, "percent_decimal_separator", Escape(nf.PercentDecimalSeparator));
    Field(o, "percent_group_separator", Escape(nf.PercentGroupSeparator));
    Field(o, "percent_group_sizes", Sizes(nf.PercentGroupSizes));
    Field(o, "percent_positive_pattern", Byte(nf.PercentPositivePattern));
    Field(o, "percent_negative_pattern", Byte(nf.PercentNegativePattern));
    Field(o, "nan_symbol", Escape(nf.NaNSymbol));
    Field(o, "positive_infinity_symbol", Escape(nf.PositiveInfinitySymbol));
    Field(o, "negative_infinity_symbol", Escape(nf.NegativeInfinitySymbol));
    o.WriteLine("        },");

    var months = Months(name, df.MonthNames);
    var abbreviatedMonths = Months(name, df.AbbreviatedMonthNames);
    var genitiveMonths = Months(name, df.MonthGenitiveNames);
    var abbreviatedGenitiveMonths = Months(name, df.AbbreviatedMonthGenitiveNames);
    // `DateTimeFormatInfoScanner.GetFormatFlagGenitiveMonth`: .NET only reaches
    // for a genitive name when the culture actually has different ones.
    var useGenitive = !months.SequenceEqual(genitiveMonths)
        || !abbreviatedMonths.SequenceEqual(abbreviatedGenitiveMonths);

    o.WriteLine("        datetime: DateTimeFormat {");
    Field(o, "month_names", Strings(months));
    Field(o, "abbreviated_month_names", Strings(abbreviatedMonths));
    Field(o, "month_genitive_names", Strings(genitiveMonths));
    Field(o, "abbreviated_month_genitive_names", Strings(abbreviatedGenitiveMonths));
    Field(o, "use_genitive_month", useGenitive ? "true" : "false");
    Field(o, "day_names", Strings(Days(name, df.DayNames)));
    Field(o, "abbreviated_day_names", Strings(Days(name, df.AbbreviatedDayNames)));
    Field(o, "era_name", Escape(df.GetEraName(df.Calendar.Eras[0])));
    Field(o, "am_designator", Escape(df.AMDesignator));
    Field(o, "pm_designator", Escape(df.PMDesignator));
    Field(o, "date_separator", Escape(df.DateSeparator));
    Field(o, "time_separator", Escape(df.TimeSeparator));
    Field(o, "short_date_pattern", Escape(df.ShortDatePattern));
    Field(o, "long_date_pattern", Escape(df.LongDatePattern));
    Field(o, "short_time_pattern", Escape(df.ShortTimePattern));
    Field(o, "long_time_pattern", Escape(df.LongTimePattern));
    Field(o, "month_day_pattern", Escape(df.MonthDayPattern));
    Field(o, "year_month_pattern", Escape(df.YearMonthPattern));
    Field(o, "full_date_time_pattern", Escape(df.FullDateTimePattern));
    o.WriteLine("        },");
    o.WriteLine("    },");
}

static void Field(TextWriter o, string name, string value) =>
    o.WriteLine($"            {name}: {value},");

/// A `[&str; 12]` / `[&str; 7]` literal.
static string Strings(string[] values) =>
    "[" + string.Join(", ", values.Select(Escape)) + "]";

/// .NET pads month arrays to 13 for the calendars that have a leap month. A
/// non-empty 13th entry means the culture's calendar does not fit the port's
/// 12-month `DateTimeFormat`, so fail rather than silently drop it.
static string[] Months(string culture, string[] values)
{
    if (values.Length != 13 || values[12].Length != 0)
    {
        throw new InvalidOperationException(
            $"'{culture}' has a 13-month calendar ({values.Length} names, 13th '{values[^1]}')");
    }
    return values[..12];
}

static string[] Days(string culture, string[] values)
{
    if (values.Length != 7)
    {
        throw new InvalidOperationException($"'{culture}' has {values.Length} day names, not 7");
    }
    return values;
}

/// .NET `NumberGroupSizes` and friends, as a Rust `&[u8]`.
static string Sizes(int[] sizes)
{
    foreach (var size in sizes)
    {
        if (size is < 0 or > byte.MaxValue)
        {
            throw new InvalidOperationException($"group size {size} does not fit a u8");
        }
    }
    return "&[" + string.Join(", ", sizes) + "]";
}

/// A .NET pattern index (`CurrencyNegativePattern`, …) as a Rust `u8`.
static string Byte(int value)
{
    if (value is < 0 or > byte.MaxValue)
    {
        throw new InvalidOperationException($"value {value} does not fit a u8");
    }
    return value.ToString(CultureInfo.InvariantCulture);
}

/// A Rust string literal.
///
/// Letters and digits stay literal, so month and day names read as themselves.
/// Everything else outside printable ASCII becomes `\u{...}`, because that is
/// where real culture data hides characters no reviewer could otherwise tell
/// apart: U+202F narrow no-break space between `fr` digit groups, U+00A0 in
/// `ru`, U+2212 minus in `sv`, U+200F/U+061C bidi marks all over `ar`. The
/// escape is what keeps a copy-paste or an editor's "trim whitespace" from
/// silently changing what we format.
static string Escape(string value)
{
    var sb = new StringBuilder("\"");
    foreach (var c in value)
    {
        switch (c)
        {
            case '\\': sb.Append(@"\\"); break;
            case '"': sb.Append("\\\""); break;
            default:
                if (c is >= ' ' and <= '~' || char.IsLetter(c) || char.IsDigit(c))
                {
                    sb.Append(c);
                }
                else
                {
                    sb.Append("\\u{").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture)).Append('}');
                }
                break;
        }
    }
    return sb.Append('"').ToString();
}
