//! Replays the checked-in golden corpus through this tool's own two halves.
//!
//! `src/rustside.rs` is a copy of `crates/smartformat/tests/goldens.rs` — the
//! same argument mapping, the same settings, the same fixtures — and a copy
//! drifts. Running all of `goldens/m1.json` back through it, and comparing with
//! the same rules a campaign compares with, is what catches the drift: if the
//! two files disagree about how a `settings` key is applied, this fails while
//! the golden suite stays green and nobody notices.
//!
//! It is also the only real-world test the classifier gets. Every case in the
//! corpus that this port deliberately does not match is skipped in the golden
//! suite with a reason, and those reasons are exactly what
//! `classify::known_divergence` recognises the shape of. A disagreement here
//! that the classifier calls *new* is therefore either a divergence nobody
//! wrote down or a rule that does not fire — both worth knowing, so the test
//! names them.

use std::collections::BTreeMap;

use difffuzz::case::{Case, NetOutcome};
use difffuzz::classify::{self};
use difffuzz::gen::{Node, Template};
use difffuzz::rustside;
use serde_json::{Map, Value as Json};

const GOLDENS: &str = include_str!("../../../goldens/m1.json");

/// How many golden cases the classifier is allowed to call *new*.
///
/// It is zero, and it earns being zero: every case the corpus records as a
/// deliberate divergence is one `classify::known_divergence` recognises from
/// the outside, without an id to look it up by. Raising this number is a way of
/// saying a rule was not worth writing, which is a decision to take on purpose
/// rather than by leaving a test yellow.
const UNRECOGNISABLE_FROM_THE_OUTSIDE: usize = 0;

#[test]
fn the_golden_corpus_replays_through_this_tools_own_renderer() {
    let document: Json = serde_json::from_str(GOLDENS).expect("the golden file is valid JSON");
    let cases = document["cases"].as_array().expect("a cases array");
    let now = document["now"].as_str().expect("the pinned clock");
    assert!(cases.len() > 2000, "the corpus shrank unexpectedly");

    let mut agreements = 0;
    let mut known: BTreeMap<&str, usize> = BTreeMap::new();
    let mut unexplained: Vec<String> = Vec::new();

    for golden in cases {
        let case = Case {
            id: golden["id"].as_str().expect("an id").to_string(),
            // A literal node renders verbatim, which is how a template that was
            // not generated by the grammar gets into a `Case`.
            tree: Template {
                nodes: vec![Node::Literal(
                    golden["template"].as_str().expect("a template").to_string(),
                )],
            },
            args: golden["args"].clone(),
            culture: golden["culture"].as_str().expect("a culture").to_string(),
            settings: golden["settings"]
                .as_object()
                .cloned()
                .unwrap_or_else(Map::new),
        };

        let expected = &golden["expected"];
        let net = if let Some(result) = expected["result"].as_str() {
            NetOutcome::Result(result.to_string())
        } else if let Some(error) = expected["error"].as_str() {
            NetOutcome::Error(error.to_string())
        } else {
            panic!("case {} has neither a result nor an error", case.id);
        };

        let rust = rustside::render(&case, now);
        if classify::agrees(&case, &net, &rust) {
            agreements += 1;
            continue;
        }
        match classify::known_divergence(&case, &net, &rust) {
            Some(recognised) => *known.entry(recognised.rule).or_default() += 1,
            None => unexplained.push(format!(
                "{}: template {:?}\n    .NET {net}\n    rust {rust}",
                case.id,
                case.template()
            )),
        }
    }

    eprintln!("{agreements} of {} golden cases agree", cases.len());
    for (rule, count) in &known {
        eprintln!("  {count:>3} recognised by {rule}");
    }

    // The corpus is what this port is built to match, so almost all of it has
    // to agree here or `src/rustside.rs` has drifted from the golden runner.
    let floor = cases.len() * 95 / 100;
    assert!(
        agreements >= floor,
        "only {agreements} of {} golden cases agree, which is below {floor}: \
         src/rustside.rs has probably drifted from crates/smartformat/tests/goldens.rs\n{}",
        cases.len(),
        unexplained.join("\n")
    );

    assert_eq!(
        unexplained.len(),
        UNRECOGNISABLE_FROM_THE_OUTSIDE,
        "{} golden cases disagree in a way the classifier does not recognise, \
         and it is allowed {UNRECOGNISABLE_FROM_THE_OUTSIDE}:\n{}",
        unexplained.len(),
        unexplained.join("\n")
    );
}
